---
output: 
  pdf_document:
    latex_engine: xelatex
    template: latex_temp/template.tex
    includes: 
      in_header: latex_temp/header.tex
geometry: margin=0.5in

title: "CV"
author: Chi-Lin Yu

address: "N211, Psychology Department, National Taiwan University, No. 1, Sec. 4, Roosevelt Rd., Taipei, Taiwan"
fontawesome: no
email: psychilinyu@gmail.com
phone: "+886-970992503"
github: PsyChiLin
web: psychilin.github.io
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# EDUCATION

National Taiwan University (NTU), Taipei, Taiwan \hfill 2017/2-2018/6

Degree: M.S. Psychology (Thesis: *“Neural Correlates of Theory of Mind in Typically Developing Youths and Youths with Autism Spectrum Disorder”*)

National Cheng Kung University (NCKU), Tainan, Taiwan  \hfill 2012/9-2016/7

Degree: B.S. Psychology

# PROFESSIONAL EXPERIENCE

## NTU, Language Neuroscience Laboratory (Mentor: Prof. Tai-Li Chou) \hfill 2017/2-Now

-- Develop functional magnetic resonance imaging (fMRI) studies to investigate the underlying mechanism of social cognition in typical developing children.

-- Identify aberrant cognitive organizations in patients with autism spectrum disorder (ASD) and propose a framework for their atypical social processing.

-- Understand the differences in neural correlates of semantic processing between typical developing subjects and schizophrenia patients.

-- Investigate language comprehension and the corresponding neural activities in bilingual adults.

-- Design a new analysis method that implement machine learning algorithms to analyze near functional infrared spectroscopy (fNIRS) data.

-- Establish a model to interpret the mechanism of human empathy.

## NCKU, Cognitive and Affective Neuroscience Laboratory (Mentor: Prof. Der-Yow Chen) \hfill 2014/9-Now

-- Develop a hyper-scanning paradigm with multi-fMRI scanners to investigate the neural underpinnings of social interaction.

-- Probe the underlying mentalizing processes and cognitive abilities of playing Chinese Go from the experimental psychology and artificial intelligence perspectives.

-- Investigate the relationship between perspective taking and emotion processing using interactive social decision-making tasks.

## NCKU, Institute of Education (Mentor: Prof. Ching-Fan Sheu) \hfill 2016/2-Now

-- Design an user-friendly web application for exploratory factor analysis (EFA) by using shiny package in R.

-- Develop exploratory graphical tools for Event Related Potentials (ERPs) and fNIRS data analysis.

-- Establish education programs for teaching statistics, markdown, and R
 
## NTHU (National Tsing Hua University), Center for General Education (Mentor: Prof. Shu-Hui Lee) \hfill 2017/11-Now

-- Develop fMRI studies to explore the neural correlates of Chinese classifiers in typical developing children.

-- Design behavioral and neuroimaging experiments to investigate the aberrant neural mechanisms of Theory of Mind and emotion-related semantic processing in patients with alexithymia.

-- Investigate neural correlates of reward processing in individuals with Attention Deficit Hyperactivity Disorder (ADHD)

## NCKU, Language Acquisition and Cognitive Development Laboratory (Mentor: Prof. Jon-Fan Hu) \hfill 2014/9-Now

-- Pioneer fNIRS research in Taiwan to explore the neural mechanism of first impression formation.

-- Adopt behavioral experiments in embodied perspective to probe semantic properties of emotion words.

-- Develop fMRI studies to investigate the underlying relationships between ToM and humor processing.

-- Establish valid and reliable scales to measure self-report empathy ability.

-- Design developmental experiments to understand the interaction between Theory of Mind, empathy and social development.

# PUBLICATIONS

## Journal Articles

Chen, D. Y., **Yu, C. L.**, Su, C. W., Liao, K. H., & Hsiao, H. Y. (Accepted). Cognitive Abilities in the Game of Go during the Opening, Middle, and Endgame Phases: When Experimental Psychology Meets Artificial Intelligence. This paper has been accepted in *Chinese Journal of Psychology* on 2018/10/26 and will be available soon (*As the co-first author*).

**Yu, C. L.** & Chou, T. L. (2018). A Dual Route Model of Empathy: A Neurobiological Prospective. *Frontiers in Psychology*, *9*(2212), 1-5.


**Yu, C. L.**, & Sheu, C. F. (2018). EFAshiny: An User-Friendly Shiny Application for Exploratory Factor Analysis. *Journal of Open Source Software*, *3*(22), 567.

**Yu, C. L.**, Wang, M. Y., & Hu, J. F. (2016). Valence processing of first impressions in the dorsomedial prefrontal cortex: a near-infrared spectroscopy study. *NeuroReport*, *27*(8), 574-579.

## Journal Articles : Under Review/Revision

**Yu, C. L.**, Chen, H. C., Yang, Z. Y., & Chou, T. L. “Multi-Time Points Analysis: A Time Course Analysis with Functional Near-Infrared Spectroscopy”

Hu, J. F., **Yu, C. L.**, Tsai Y. L., Hsiao, Y. R. & Chen, H. C. “The Role of Theory of Mind Ability in Verbal Humor Comprehension: A functional magnetic resonance imaging study” (*As the corresponding author*)
  
## Journal Articles : In Preparation

**Yu, C. L.**, Lee, S. H., Gau S., & Chou, T. L. “Neural Correlates of Theory of Mind in Typically Developing Youths and Youths with Autism Spectrum Disorder”

**Yu, C. L.**, Causeur D., Shen, I. H., & Sheu, C. F. “ggerp: Visualization of Event-Related Brain Potentials with ggplot2”

**Yu, C. L.**, Wang, M. Y., & Hu, J. F. “Early Development of the Relationship between Empathy and Theory of Mind” (*As the co-first author*)

**Yu, C. L.**, Hu, J. F., Chu, C. & Chuang Y. Y. “The Impact of Facial Expressions On the Rating of Valence, Arousal, and Typicality for Positive and Negative Emotion Words: An Embodied Cognition Approach”

Hu, J. F., **Yu, C. L.**, Hsiao, Y. R., Chou, L. F. & Wang, P, L. “The Development of Chinese version of Empathy Quotient”

## Conference Presentations

**Yu, C. L.**, Lee, S. H., Chen T., Liao, C. C. (2019) "The Influence of Family Reading History on Chinese Classifier Processing: An fMRI Study", will be presented as a poster in the 2019 Annual Meeting of Organization for Human Brain Mapping (OHBM).

**Yu, C. L.**, Hwang, T. J., Chou, T. L. (2018) "Neural Changes Associated with Semantic Processing in Aged Schizophrenia", presented as a poster in the 17th International Conference on the Processing of East Asian Languages and the 9th Conference on Language, Discourse, and Cognition (ICPEAL 17 – CLDC 9).

**Yu, C. L.**, Lee, S. H., Gau S., & Chou, T. L. (2018) "Aberrant Neural Organization of Theory of Mind in Youths with Autism", presented as a poster in the 2018 Annual Meeting of Organization for Human Brain Mapping (OHBM).

**Yu, C. L.**, Chen, H. C., Yang, Z. Y., & Chou, T. L. (2018) “Multi-Time Points Analysis: A Time Course Analysis with Functional Near-Infrared Spectroscopy”, presented as a poster in the 3rd NTU-Kyoto University International Symposium for Cognitive Neuroscience.

**Yu, C. L.** & Sheu, C. F. (2017). “EFAshiny: A shiny application for exploratory factor analysis”, presented as a poster in 47th annual meeting of the Society for Computers in Psychology (SCiP).

**Yu, C. L.**, Causeur, D., Lee, Y. s. & Sheu, C. F. (2017). “ggerp: An R Package for Graphical Explorations of Event-Related Potentials ”, presented as oral presentation in a symposium of 55th Annual Taiwan Psychology Association Meeting.

**Yu, C. L.**, Causeur, D., Shen, I. H. & Sheu, C. F. (2016). “Using R to explore ERP data”, presented as oral presentation in a symposium of 46th annual meeting of the Society for Computers in Psychology (SCiP).

**Yu, C. L.**, Wang, M. Y., Chen, P. W., Yap, J. Y., Chang, J. S., Hsiao, Y. R. & Hu, J. F (2015). “Using false belief task to explore the effect of empathy situation on theory of mind function”, presented as a poster at the 37th Annual Cognitive Science Society Meeting.

Chu, C., **Yu, C. L.**, Chuang Y. Y., Tsai Y. L. & Hu, J. F. (2015). “An Embodied Cognition Approach to Studying Emotional Words:The Impact of Positive Facial Experiences on Semantic Properties Judgment”, presented as a poster at the 37th Annual Cognitive Science Society Meeting.

Tsai Y. L.,**Yu, C. L.**, Hsiao, Y. R., Cho, S. L., Chen, H. C. & Hu, J. F. (2015). “The differences of semantic features between Chinese concrete, abstract, and emotional concept”, presented as a poster at the 37th Annual Cognitive Science Society Meeting.

Chuang Y. Y., **Yu, C. L.**, Chu, C., Tsai Y. L. & Hu, J. F.(2015) “An Embodied Cognition Approach to Studying the Impact of Negative Facial Experiences on Semantic Properties of Emotional Words”, presented as a poster at the 8th Annual Conference on Embodied and Situated Language Processing.

Chen S. C., Hu, J. F., Chuang Y. Y., Chu, C., & **Yu, C. L.** (2015). “Releasing Strength in Imagination Constructs Implicit Association of Simulated Action and Response Index”, presented as a poster at the 8th Annual Conference on Embodied and Situated Language Processing.


# TEACHING EXPERIENCE

2018 Teaching Assistant, Brain and Language Course (English-Taught), Mentor: Prof. Tai-Li Chou

2017 Teaching Assistant, General Psychology Course, Mentor: Prof. Tai-Li Chou

2016 Teaching Assistant, Cognitive Neuroscience Course, Mentor: Prof. Shu-Lan Hsieh

2016 Teaching Assistant, Assessment Practicum Developmental Psychology Course, Mentor: Prof. Jon-Fan Hu

2016 Teaching Assistant, Seminar on Emotion and Memory Course, Mentor: Prof. Der-Yow Chen

# AWARDS & HONORS

2018 Taiwan Government PhD Scholarship for Studying Abroad: 4 years full funding for studying PhD in U.S. 

-- *This funding supports the best student in psychology/neuroscience domain. Only one student will get the scholarship each year.*

2018 Best paper award for Annual Meeting of Taiwanese Society of Child and Adolescent Psychiatry

2018 An International Conference Travel Grant from Taiwan Ministry of Science and Technology 
2016 NCKU President Wei-Noon Wang Memorial Scholarship

2016 KYMCO Scholarship for outstanding student

2016 Ren-Da Industrial Park outstanding student scholarship

2016 Rank 1st in the class of NCKU psychology department in 2015~2016 academic year 

2015 The title of outstanding student for the academic achievement

2015 Rank 1st in the class of NCKU psychology department in 2014~2015 academic year

2015 Tainan True Jesus Church outstanding student scholarship

2015 Taiwan Ministry of Science and Technology Research Scholarship (Students : Wang, M. Y. , Yu, C. L., et al.; Project Number:104-2815-C-006-149–H)

2014 Tainan True Jesus Church outstanding student scholarship

2014 The second place award of posters in the Experimental Psychology Course

# SKILLS

Languages: Mandarin: Native Fluency; English/Taiwanese: Excellent Fluency
   
Experimental skill: Experimental Design, Imaging Data Analysis, Scale Design and Analysis, Statistical Modeling

Computer programing: R, MATLAB, SPM, E-PRIME, HOMER, Oro.Nifti, ANTsR, fslR

# SELECTED EXTRACURRICULAR

2018 Volunteer Assistant, The 17th International Conference on the Processing of East Asian Languages and the 9th Conference on Language, Discourse, and Cognition (ICPEAL 17 – CLDC 9)

2016 Valedictorian, Department of Psychology, NCKU

2015 Representatives of Students in School, Department of Psychology, NCKU

2015 Chief Counselor, Psychology Summer Camp, NCKU

2015 Volunteer Assistant, The 7th Annual Taiwan Association of Clinical Psychology Meeting 

2015 Symposium Student for resting state fMRI, Mind Research and imaging center, NCKU

2015 Symposium Student for Cognitive Neuroscience of Aging, Mind Research and imaging center,
NCKU

2014 Activity Leader, The Night of Psychology, NCKU

2013 Leader, The Week of Psychology, NCKU